In [166]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle
from apyori import apriori

In [167]:
base_mercado1 = pd.read_csv("mercado.csv",header=None)
base_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

In [168]:
transacoes = []
for i in range(len(base_mercado1)):
    transacoes.append([str(base_mercado1.values[i,j]) for j in range(4)])

In [169]:
transacoes

[['leite', 'cerveja', 'pao', 'manteiga'],
 ['cafe', 'pao', 'manteiga', 'nan'],
 ['cafe', 'pao', 'manteiga', 'nan'],
 ['leite', 'cafe', 'pao', 'manteiga'],
 ['cerveja', 'nan', 'nan', 'nan'],
 ['manteiga', 'nan', 'nan', 'nan'],
 ['pao', 'nan', 'nan', 'nan'],
 ['feijao', 'nan', 'nan', 'nan'],
 ['arroz', 'feijao', 'nan', 'nan'],
 ['arroz', 'nan', 'nan', 'nan']]

In [170]:
regras = apriori(transacoes, min_support = 0.3, min_confidence = 0.8, min_lift = 2)
resultados = list(regras)
resultados

[RelationRecord(items=frozenset({'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]),
 RelationRecord(items=frozenset({'cafe', 'pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)]),
 RelationRecord(items=frozenset({'cafe', 'pao', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])]

In [171]:
r = resultados[2][2]
r

[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0),
 OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]

In [172]:
r[2]

OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)

In [173]:
r[2][0]

frozenset({'cafe', 'pao'})

In [174]:
r[2][1]

frozenset({'manteiga'})

In [175]:
r[2][2]

1.0

In [176]:
A = []
B = []
suporte = []
confianca = []
lift = []

for resultado in resultados:
  #print(resultado)
  s = resultado[1]
  #print(s)
  result_rules = resultado[2]
  #print(result_rule)
  for result_rule in result_rules:
    #print(result_rule)
    a = list(result_rule[0])
    b = list(result_rule[1])
    c = result_rule[2]
    l = result_rule[3]
    #print(a, ' - ', b, ' - ', c, ' - ', l)
    A.append(a)
    B.append(b)
    suporte.append(s)
    confianca.append(c)
    lift.append(l)

In [177]:
rules_df = pd.DataFrame({"A":A,"B":B,"suporte":suporte,"confiança":confianca,"lift":lift})

In [178]:
rules_df.sort_values(by= "lift",ascending=False)

                  A                B  suporte  confiança  lift
2            [cafe]  [pao, manteiga]      0.3        1.0   2.5
0            [cafe]       [manteiga]      0.3        1.0   2.0
1            [cafe]            [pao]      0.3        1.0   2.0
3  [cafe, manteiga]            [pao]      0.3        1.0   2.0
4       [cafe, pao]       [manteiga]      0.3        1.0   2.0

#BASE MERCADO 2

In [179]:
base_mercado2 = pd.read_csv("mercado2.csv",header=None)
base_mercado2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [180]:
transacoes2 = []
for i in range(base_mercado2.shape[0]):
    transacoes2.append([str(base_mercado2.values[i,j]) for j in range(base_mercado2.shape[1])])

In [181]:
regras2 = apriori(transacoes2,min_support = 0.003, min_confidence = 0.2, min_lift = 3)
resultados2 = list(regras2)

In [182]:
A2 = []
B2 = []
suporte2 = []
confianca2 = []
lift2 = []

for resultado2 in resultados2:
  #print(resultado)
  s2 = resultado2[1]
  #print(s)
  result_rules2 = resultado2[2]
  #print(result_rule)
  for result_rule2 in result_rules2:
    #print(result_rule)
    a2 = list(result_rule2[0])
    b2 = list(result_rule2[1])
    c2 = result_rule2[2]
    l2 = result_rule2[3]
    #print(a, ' - ', b, ' - ', c, ' - ', l)
    A2.append(a2)
    B2.append(b2)
    suporte2.append(s2)
    confianca2.append(c2)
    lift2.append(l2)

In [183]:
rules_df2 = pd.DataFrame({"A":A2,"B":B2,"suporte":suporte2,"confiança":confianca2,"lift":lift2})

In [185]:
rules_df2.sort_values(by= "confiança",ascending=False)

,A,B,suporte,confiança,lift
347,"[milk, frozen vegetables, soup]","[nan, mineral water]",0.003066,0.766667,3.218112
353,"[milk, frozen vegetables, nan, soup]",[mineral water],0.003066,0.766667,3.216312
180,"[milk, frozen vegetables, soup]",[mineral water],0.003066,0.766667,3.216312
106,"[ground beef, nan, cereals]",[spaghetti],0.003066,0.676471,3.885303
104,"[ground beef, cereals]","[nan, spaghetti]",0.003066,0.676471,3.885303
...,...,...,...,...,...
358,"[shrimp, frozen vegetables]","[nan, spaghetti, mineral water]",0.003333,0.200000,3.348661
371,"[milk, ground beef, nan]","[spaghetti, mineral water]",0.004399,0.200000,3.348661
370,"[milk, ground beef]","[nan, spaghetti, mineral water]",0.004399,0.200000,3.348661
224,"[milk, ground beef]","[spaghetti, mineral water]",0.004399,0.200000,3.348661
360,"[shrimp, nan, frozen vegetables]","[spaghetti, mineral water]",0.003333,0.200000,3.348661